# Rust formatting configuration for niri-spacer

# Edition-based formatting
edition = "2021"

# Line length
max_width = 100
comment_width = 100

# Function and struct formatting
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
where_single_line = true

# Import formatting
imports_layout = "Vertical"
group_imports = "StdExternalCrate"
reorder_imports = true

# Whitespace and alignment
tab_spaces = 4
use_small_heuristics = "Default"
indent_style = "Block"
wrap_comments = true
format_code_in_doc_comments = true

# String formatting
format_strings = true
format_macro_matchers = true

# Trailing comma
trailing_comma = "Vertical"
match_block_trailing_comma = true

# Spacing
spaces_around_ranges = false
type_punctuation_density = "Compressed"

# Other options
unstable_features = false
remove_nested_parens = true
normalize_comments = true
normalize_doc_attributes = true
