# Rust formatting configuration for niri-spacer

# Edition-based formatting
edition = "2021"

# Line length
max_width = 100

# Function and struct formatting
fn_params_layout = "Tall"

# Import formatting
reorder_imports = true

# Whitespace and alignment
tab_spaces = 4
use_small_heuristics = "Default"

# Trailing comma
match_block_trailing_comma = true

# Other options
remove_nested_parens = true
