#!/bin/bash
set -euo pipefail

UPDATE_URL="https://github.com/wlritchi/env"

wlr-working 'update check'

# find remote for non-interactive updates
update_remote=
while IFS= read remote <&3; do
    if [ "$(git -C "$WLR_ENV_PATH" remote get-url "$remote")" == "https://github.com/wlritchi/env" ]; then
        update_remote="$remote"
        break
    fi
done 3< <( git -C "$WLR_ENV_PATH" remote )

if [ -z "$update_remote" ]; then
    git -C "$WLR_ENV_PATH" remote add updates "$UPDATE_URL"
    update_remote=updates
fi

git -C "$WLR_ENV_PATH" fetch "$update_remote"
local_commit="$(git -C "$WLR_ENV_PATH" rev-parse HEAD)"
remote_commit="$(git -C "$WLR_ENV_PATH" rev-parse "$update_remote/main")"

# check signature
if ! "$WLR_ENV_PATH/bin/crypto/git-gpg-self" -C "$WLR_ENV_PATH" verify-commit "$remote_commit"; then
    wlr-error 'update failed, bad signature'
    exit 1
fi

# if nothing to do, exit early
if [ "$local_commit" == "$remote_commit" ] && [ "${1:-}" != '--force' ]; then
    wlr-good 'update check succeeded, no new changes'
    exit 0
fi

git -C "$WLR_ENV_PATH" merge --ff-only "$remote_commit"

# check for new symlinks in dotfiles

print_diff() {
    if command -v colordiff >/dev/null 2>&1; then
        colordiff "$@" || true
    else
        diff "$@" || true
    fi
}

sync_dir() {
    local parent="${1%/*}"
    if [ "$parent" != "$relative" ]; then
        sync_dir "$parent"
    fi
    if [ -d "$HOME/$1" ]; then
        expected_permissions="$(stat -c '%a' "$WLR_ENV_PATH/dotfiles/$1")"
        actual_permissions="$(stat -c '%a' "$HOME/$1")"
        if [ "$expected_permissions" != "$actual_permissions" ]; then
            if wlr-ask "Update permissions on $HOME/$1 to $expected_permissions (currently $actual_permissions)?"; then
                chmod "$expected_permissions" "$HOME/$1"
            fi
        fi
    elif [ -e "$HOME/$1" ]; then
        wlr-warn "update: $HOME/$1 exists, but is not a directory"
    else
        cp -r "$WLR_ENV_PATH/dotfiles/$1" "$HOME/$1"
    fi
}

link_file() {
    if [ -L "$HOME/$1" ]; then
        expected_target="$(realpath "$WLR_ENV_PATH/dotfiles/$1")"
        actual_target="$(realpath "$HOME/$1")"
        if [ "$expected_target" != "$actual_target" ]; then
            print_diff "$HOME/$1" "$WLR_ENV_PATH/dotfiles/$1"
            if wlr-ask "Update symlink $HOME/$1 to point to $WLR_ENV_PATH/dotfiles/$1 (currently $actual_target)?"; then
                ln -sf "$WLR_ENV_PATH/dotfiles/$1" "$HOME/$1"
            fi
        fi
    elif [ -f "$HOME/$1" ]; then
        print_diff "$HOME/$1" "$WLR_ENV_PATH/dotfiles/$1"
        if wlr-ask "Replace $HOME/$1 with a symlink to $WLR_ENV_PATH/dotfiles/$1?"; then
            ln -sf "$WLR_ENV_PATH/dotfiles/$1" "$HOME/$1"
        fi
    elif [ -e "$HOME/$1" ]; then
        wlr-warn "update: $HOME/$1 exists, but is not a regular file or symlink"
    else
        ln -s "$(realpath "$WLR_ENV_PATH/dotfiles/$1")" "$HOME/$1"
    fi
}

while IFS= read filename <&3; do
    relative="${filename#"$WLR_ENV_PATH/dotfiles/"}"
    if [ "$relative" == "$filename" ]; then
        wlr-warn "update: failed to match filename $filename against expected subdirectory"
        continue
    fi
    dir="${relative%/*}"
    if [ "$dir" != "$relative" ]; then
        sync_dir "$dir"
    fi
    link_file "$relative"
done 3< <( find "$WLR_ENV_PATH/dotfiles/" -type f 2>/dev/null || true )

wlr-good 'update succeeded'
