#!/bin/bash
set -euo pipefail

upstream
if [ "$#" -eq 0 ]; then
    if upstream="$(git rev-parse --abbrev-ref --symbolic-full-name @{u})"; then
        git rebase -i --rebase-merges "$upstream"
    else
        return 1
    fi
else
    git rebase -i --rebase-merges "$@"
fi
